#!/bin/bash
# Resolve a thumbnail for one file and print its path. No output means there is
# no picture to be had, and the overlay keeps showing its glyph.
#
# Two places are looked at, in this order:
#
#   1. The shared freedesktop cache, ~/.cache/thumbnails/<size>/<md5>.png. This
#      is the one Nautilus and every other file manager fills, so a PDF that
#      has been looked at once already has a thumbnail sitting there and this
#      costs a stat.
#   2. Our own cache, for everything else. A thumbnail is generated by the
#      system thumbnailer registered for the file's type -- the same programs
#      the file managers call -- and kept under XDG_CACHE_HOME. Writing into
#      the shared cache instead would mean writing entries without the
#      Thumb::URI and Thumb::MTime metadata the spec asks for, which other
#      readers would rightly throw away.

set -o pipefail

path="${1:-}"
size="${2:-1024}"
[[ -n $path && -f $path && -r $path ]] || exit 0

cache_home="${XDG_CACHE_HOME:-$HOME/.cache}"
shared="$cache_home/thumbnails"
ours="$cache_home/omarchy-filesearch/thumbnails"

# Percent-encoding the way GLib does it, because the cache name is the md5 of
# the URI GLib produced. LC_ALL=C so the loop walks bytes: a character outside
# ASCII is several of them, and each one is escaped on its own.
uri_of() {
  local LC_ALL=C text=$1 out="" i char
  for ((i = 0; i < ${#text}; i++)); do
    char=${text:i:1}
    case "$char" in
    [-a-zA-Z0-9_.~/!\$\&\'\(\)\*+,\;=:@]) out+=$char ;;
    *)
      printf -v char '%%%02X' "'$char"
      out+=$char
      ;;
    esac
  done
  printf 'file://%s' "$out"
}

uri=$(uri_of "$path")
key=$(printf '%s' "$uri" | md5sum) || exit 0
key=${key%% *}

# Largest first: every one of these is a valid thumbnail, and the overlay
# would rather scale one down than up. A cached file older than the file it
# depicts describes a version that no longer exists -- the spec stores the
# source mtime in the PNG for this, but the cache entry's own timestamp
# answers the same question without parsing anything.
for dir in "$shared/xx-large" "$shared/x-large" "$shared/large" "$shared/normal" "$ours"; do
  candidate="$dir/$key.png"
  if [[ -f $candidate && $candidate -nt $path ]]; then
    printf '%s\n' "$candidate"
    exit 0
  fi
done

# Nothing cached, so make one. The type decides which thumbnailer can, and
# gio reads it the same way the file managers do.
mime=$(gio info -a standard::content-type "$path" 2>/dev/null | sed -n 's/^ *standard::content-type: *//p' | head -1)
[[ -n $mime ]] || exit 0

# The Exec line comes from a system file and holds no user data, so splitting
# it into words is safe. The paths that replace the field codes never are, and
# each one stays a single argument.
run_thumbnailer() {
  local mimes="" exec_line="" tryexec="" line file dir i
  for dir in "${XDG_DATA_HOME:-$HOME/.local/share}/thumbnailers" /usr/local/share/thumbnailers /usr/share/thumbnailers; do
    [[ -d $dir ]] || continue
    for file in "$dir"/*.thumbnailer; do
      [[ -f $file ]] || continue

      mimes="" exec_line="" tryexec=""
      # `|| [[ -n $line ]]` because read reports failure on a last line with no
      # newline after it, and .thumbnailer files in the wild end that way --
      # the one that handles every video format on this machine among them.
      while IFS= read -r line || [[ -n $line ]]; do
        case "$line" in
        Exec=*) exec_line=${line#Exec=} ;;
        MimeType=*) mimes=${line#MimeType=} ;;
        TryExec=*) tryexec=${line#TryExec=} ;;
        esac
      done <"$file"

      # Semicolons on both ends so the first and last entry match like any
      # other, whether or not the list ends in one.
      [[ -n $exec_line && ";$mimes;" == *";$1;"* ]] || continue
      [[ -z $tryexec ]] || command -v -- "$tryexec" >/dev/null 2>&1 || continue

      local argv=()
      read -r -a argv <<<"$exec_line"
      for i in "${!argv[@]}"; do
        case "${argv[i]}" in
        %s) argv[i]=$size ;;
        %u) argv[i]=$uri ;;
        %i) argv[i]=$path ;;
        %o) argv[i]=$2 ;;
        esac
      done

      # A thumbnailer that wedges on a damaged file must not wedge the overlay.
      timeout 20 "${argv[@]}" >/dev/null 2>&1 && return 0
    done
  done
  return 1
}

mkdir -p "$ours" 2>/dev/null || exit 0
tmp=$(mktemp "$ours/.pending-XXXXXX.png" 2>/dev/null) || exit 0
trap 'rm -f "$tmp"' EXIT

run_thumbnailer "$mime" "$tmp" || exit 0
# An empty file is what a thumbnailer leaves behind when it gave up without
# saying so.
[[ -s $tmp ]] || exit 0

# Into place in one step, so a reader never opens a half-written PNG.
chmod 600 "$tmp" 2>/dev/null
mv -f "$tmp" "$ours/$key.png" || exit 0
trap - EXIT

printf '%s\n' "$ours/$key.png"
